In [6]:
# Code Cell [1]. 라이브러리

import numpy as np

from sklearn import datasets
from sklearn.preprocessing import StandardScaler

In [8]:
# Code Cell [2]. iris 데이터 

iris = datasets.load_iris()

X_all = iris.data
Y_all = iris.target

print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [11]:
# Code Cell [3]. 데이터 확인 

print("X shape:", X_all.shape)
print("Y shape:", Y_all.shape)

print("\nFeature Names")
print(iris.feature_names)

print("\nTarget Names")
print(iris.target_names)

X shape: (150, 4)
Y shape: (150,)

Feature Names
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Names
['setosa' 'versicolor' 'virginica']


In [12]:
# Code Cell [4]. 실제 데이터 확인 

X_all[:10]
Y_all

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
# Code Cell [5] Setosa / Versicolor 추출
   # Setosa(0)와 Versicolor(1)만 사용

mask = (Y_all == 0) | (Y_all == 1)

X = X_all[mask]
Y = Y_all[mask]

print(X.shape)
print(Y.shape)

(100, 4)
(100,)


In [15]:
# Code Cell [6] Label 확인

Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
# Code Cell [7] Label 변환

# Setosa      : +1
# Versicolor  : -1

Y = np.where(
    Y == 0,
    1,
    -1
)

Y

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [17]:
# Code Cell [8] 표준화

scaler = StandardScaler()

X = scaler.fit_transform(X)

X[:10]

array([[-0.5810659 ,  0.84183714, -1.01297765, -1.04211089],
       [-0.89430898, -0.2078351 , -1.01297765, -1.04211089],
       [-1.20755205,  0.21203379, -1.08231219, -1.04211089],
       [-1.36417359,  0.00209934, -0.94364311, -1.04211089],
       [-0.73768744,  1.05177159, -1.01297765, -1.04211089],
       [-0.11120129,  1.68157493, -0.80497402, -0.68644165],
       [-1.36417359,  0.63190269, -1.01297765, -0.86427627],
       [-0.73768744,  0.63190269, -0.94364311, -1.04211089],
       [-1.67741667, -0.41776955, -1.01297765, -1.04211089],
       [-0.89430898,  0.00209934, -0.94364311, -1.21994552]])

In [21]:
# Code Cell [9] Weight / Bias

w = np.array([
    0.5,
    0.5,
    0.5,
    0.5
])

b = 0.1

print("Weight:", w)
print("Bias:", b)

Weight: [0.5 0.5 0.5 0.5]
Bias: 0.1


In [22]:
# Code Cell [10] Feed-Forward

z = X @ w + b

print("X shape:", X.shape)
print("w shape:", w.shape)
print("z shape:", z.shape)

z

X shape: (100, 4)
w shape: (4,)
z shape: (100,)


array([-7.97158653e-01, -1.47861631e+00, -1.45997067e+00, -1.57391412e+00,
       -7.70502197e-01,  1.39478986e-01, -1.20476241e+00, -9.45769375e-01,
       -1.97513738e+00, -1.42789913e+00, -3.17624628e-01, -1.06772364e+00,
       -1.64584439e+00, -2.14140005e+00,  2.06518308e-01,  8.29912873e-01,
        8.09903664e-04, -7.08241341e-01,  1.80526756e-01, -3.58672397e-01,
       -5.63191759e-01, -3.74722310e-01, -1.22241435e+00, -6.36339354e-01,
       -9.63721830e-01, -1.33097100e+00, -7.33267481e-01, -6.84180614e-01,
       -8.23815109e-01, -1.35596886e+00, -1.38262532e+00, -4.54691677e-01,
       -1.43294579e-01,  2.50854992e-01, -1.33898182e+00, -1.25970564e+00,
       -5.18582849e-01, -9.37730278e-01, -1.90483743e+00, -8.67458607e-01,
       -8.21219380e-01, -2.47237992e+00, -1.69490298e+00, -4.50465633e-01,
       -1.31086003e-01, -1.46800977e+00, -4.12922439e-01, -1.50361417e+00,
       -3.95935396e-01, -1.08540387e+00,  2.58687195e+00,  2.13659011e+00,
        2.56184581e+00,  

In [23]:
# Code Cell [11] Step Function

y_pred = np.where(
    z >= 0,
    1,
    -1
)

y_pred

array([-1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,
       -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1])

In [24]:
# Code Cell [12] 정확도

classified = np.sum(
    y_pred == Y
)

accuracy = np.mean(
    y_pred == Y
)

print(
    f"정분류 개수: "
    f"{classified} / {len(Y)}"
)

print(
    f"Accuracy: {accuracy:.3f}"
)

정분류 개수: 12 / 100
Accuracy: 0.120


## Loss

실제값과 예측값의 차이를 확인합니다.

### Mean Squared Error (MSE)

$$
MSE = \frac{1}{N}\sum(y-\hat{y})^2
$$

### Mean Absolute Error (MAE)

$$
MAE = \frac{1}{N}\sum|y-\hat{y}|
$$

In [26]:
# Code Cell [13] Loss

mse = np.mean(
    (Y - y_pred) ** 2
)

mae = np.mean(
    np.abs(Y - y_pred)
)

print(
    f"MSE = {mse:.3f}"
)

print(
    f"MAE = {mae:.3f}"
)

MSE = 3.520
MAE = 1.760
